name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pandas=1.4.4
  - plotly=5.9.0
  - numpy=1.21.6
  - matplotlib=3.5.2
  - scikit-learn=1.0.2
  - mlxtend=0.23.1
  - seaborn=0.11.2
